# -*- coding: utf-8 -*-
from setuptools import setup

with open('README.md','r') as fh:
    long_description = fh.read()

setup(name='CoverageCompacter',
      version='1.0',
      description='Package to extrapolate coverage estimates from ultra low sequenced genomes generated by whole genome amplification (WGA) based library preparation methods',
      long_description=long_description,
      long_description_content_type="text/markdown",
      url='https://github.com/wes3985/CoverageCompacter',
      author='Wes Woollard',
      author_email='wes.woollard3985@gmail.com',
      license='MIT',
      packages=['CoverageCompacter'],
      zip_safe=False)

